### ISSUE TITLE
Blank Modal

### ISSUE THREAD

**Issue by paulmz** [Fede91/brackets-preferences-ui#20]
This extension just updated and now the View -> Preferences modal has no visible content. I'm not sure what the menu on the top-right is for, but all options there don't have an affect.

![region capture 3](https://cloud.githubusercontent.com/assets/14838047/20978089/2c32bd9a-bc6d-11e6-9fa8-cde3b0c8f1ec.png)

Currently running Brackets 1.8 build 1.8.0-17108, Preferences setup UI 2.0.0. Let me know if you need additional information.

**Comment by Fede91** [comment]
Hi Paul, the menu on top-right is not part of my plugin. This is so strange. Can you verify there are any error on Brackets console? 

Sorry for the inconvenience

**Comment by paulmz** [comment]
Hello.

Thanks for the reply. The only errors I see look like they pertain to
Brackets Preferences manager and not necessarily the plugin.

Console with extensions disabled:

[image: Inline image 1]

Beginning of long console log with extensions enabled:

[image: Inline image 2]

The Brackets console wouldn't allow to save the output like it does in
Chrome. Let me know if there's any other information I can provide.

Paul.

**Comment by Fede91** [comment]
Hi, I can't see your images but, maybe, i've found the problem.
I just updated the plugin with the 2.0.1 version.
Could you verify if the problem is solved?

Thank you.

**Comment by paulmz** [comment]
Hello.

I just updated to 2.0.1 and restarted Brackets a few times, but the modal
is still blank.

Thanks.

**Comment by Fede91** [comment]
Can I ask you the list of all plugin that you have installed on brakets? So i can reproduce your configuration? Because the plugin works on my environment.
Thanks a lot.

**Comment by paulmz** [comment]
Sure.

Brackets Color Palette v2.0.1
<https://github.com/sprintr/brackets-color-palette>
Brackets Color Picker v0.1.3
<https://github.com/mikailcolak/brackets-color-picker>
Brackets Icons v1.5.7 <https://github.com/ivogabe/Brackets-Icons>
Brackets Snippets v1.1.0 <https://github.com/jrowny/brackets-snippets>
Copy as HTML v1.0.5 <https://github.com/peterflynn/copy-as-html>
Disable Autoclose Tags v1.0.1
<https://github.com/talmand/Brackets-Disable-AutoClose-Tags>
Documents Toolbar v0.5.21
<https://github.com/dnbard/brackets-documents-toolbar>
Emmet v1.2.2 (installed but disabled) <http://emmet.io/>
Extension Highlighter v1.2.2
<https://github.com/tjeffree/Brackets-ExtensionHighlight>
Extensions Rating v0.7.4
<https://github.com/dnbard/brackets-extension-rating>
Fonts v0.0.2 <https://github.com/tirithen/brackets-fonts>
HTML Designer for Brackets v2.0.6 <https://github.com/swmitra/html-designer>
HTML Skeleton v1.4.3 <https://github.com/le717/brackets-html-skeleton>
Interactive Linter v1.0.5
<https://github.com/MiguelCastillo/Brackets-InteractiveLinter>
JSHint v2.2.19 <https://github.com/cfjedimaster/brackets-jshint>
Lorem Ipsum v1.0.3 <https://github.com/lkcampbell/brackets-lorem-ipsum>
Preferences UI Setup v2.0.1
<https://github.com/Fede91/brackets-preferences-ui>
QuickDocsJS v1.6.9 <https://github.com/Wikunia/brackets-QuickDocsJS>
Replace In Selection v1.0.0
Special HTML Characters v1.2.5
<https://github.com/thaneuk/brackets-special-html-chars>

Looking at this list makes me think I should audit my extensions... Let me
know if you need anything else. Thanks!

Paul.

**Comment by zaggino** [comment]
Same here with 2.0.1
line https://github.com/Fede91/brackets-preferences-ui/blob/master/main.js#L377
![image](https://cloud.githubusercontent.com/assets/1067319/20994301/ae6014b2-bd43-11e6-8053-89a8181995f3.png)

Console saying: `Uncaught TypeError: Cannot read property 'ass' of undefined`

**Comment by DrunkenSasquatch** [comment]
Yep. I have the same problem.

**Comment by Fede91** [comment]
Thank you all, now I try to analyze the code even if I find it hard because in my editor, the plugin works.

![screen_panel_201](https://cloud.githubusercontent.com/assets/6347651/21003256/99b622ea-bd2a-11e6-9fc0-c78685daf503.PNG)

Can I ask if you have changed your jslint settings? Because "ass" is a configuration parameter of jslint.
In the default preferences file, the jslint configurations are:

```
"jslint.options": {
	"ass": false,
	"bitwise": false,
	"browser": false,
	"closure": false,
	"continue": false,
	"couch": false,
	"debug": false,
	"devel": false,
	"eqeq": false,
	"es6": false,
	...
}
```

And in my preferences files are stored as follows:

```
"jslint.options": {
	"ass": true,
	"bitwise": false,
	"browser": false,
	"closure": false,
	"continue": false,
	"couch": false,
	"debug": false,
	"devel": false,
	"eqeq": false,
	"es6": false,
	...
}
```

This is also the same for your configurations?

**Comment by zaggino** [comment]
I deleted JSLint from my installation completely.

**Comment by Fede91** [comment]
Thank you, I didn't know it was possible, however, I suppose that the default preferences should remain the same because I used the functions provided by the program.
Now I try to manage better the system preferences.

**Comment by zaggino** [comment]
@Fede91 Maybe do a try ... catch there and just log the error into the console and don't display that one row?

**Comment by Fede91** [comment]
@zaggino yes I implement this solution. As soon as possible I'll upload the new version. Thanks!

**Comment by Fede91** [comment]
I just release the version 2.0.2 where I manage the exception of line 377. In case of error, the plugin print on console a warning message. Can you send me the screenshot of these errors?

**Comment by paulmz** [comment]
Hello. The Preferences modal appears to function normally again. Thanks!
![region capture 1](https://cloud.githubusercontent.com/assets/14838047/21014506/f9986e40-bd23-11e6-8273-4e62de8a4c08.png)

**Comment by Fede91** [comment]
Thank you for the screenshot! I see in the left some options with the brackets because  these aren't the default preferences. I'll add the translations on next release based on the list of plugin you wrote me.
